name: discord_music_bot
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - ffmpeg
  - nodejs
  - pip
  - pip:
    - discord.py[voice]
    - yt-dlp==2025.11.12
    - python-dotenv
    - spotipy
    - requests
    - beautifulsoup4
